import { Cairo, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";

const cairo = Cairo({ subsets: ["arabic"] });

export const metadata = {
  title: "Merchant Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cairo.className}>
        <Navbar />
        {children}</body>
    </html>
  );
}
