import { Cairo, Inter, Tajawal } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar";
import { ApolloClient, ApolloProvider, InMemoryCache } from "@apollo/client";
import { ApolloWrapper } from "@/lib/apollo-wrapper";


const tajawal = Tajawal({ subsets: ["arabic"], weight:["200", "300", "400", "500", "700", "900"] });

export const metadata = {
  title: "Merchant Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={tajawal.className}>
      <Navbar />
      <ApolloWrapper>{children}</ApolloWrapper>
        </body>
    </html>
  );
}
