import img1 from '../public/img/Rectangle214.jpg';
import img2 from '../public/img/Rectangle216.jpg';
import img3 from '../public/img/Rectangle218.jpg';
import img4 from '../public/img/Rectangle226.jpg';
import img5 from '../public/img/Rectangle220.jpg';
import img6 from '../public/img/Rectangle224.jpg';
import img7 from '../public/img/image_65f96a2d8929b.png';
import img8 from '../public/img/image_65f96a9836913.png';
import img9 from '../public/img/image_65f96eae9eb40.png';
import img10 from '../public/img/image_65fa0efa73350.png';
import img11 from '../public/img/image_65fa0fdf26c71.png';
import img12 from '../public/img/image_65fa1064792ac.png';
import img13 from '../public/img/image_65fa11ac455ad.png';
import img14 from '../public/img/image_65fa1510cbe65.png';
import img15 from '../public/img/image_65fa1571db594.png';
import img16 from '../public/img/image_65fa163d0527d.png';
import img17 from '../public/img/image_65fa163d0527d.png';
import img18 from '../public/img/image_6601ccfb0e6d7.jpg';
import img19 from '../public/img/image_6601cef877eb8.png';
import img20 from '../public/img/image_6602994d97685.jpg';
import img21 from '../public/img/image_660299d8695ae.png';

export const products = [
  {
    id: 1,
    img: img1,
    amount: '4',
    price: '30',
    nameArabic: 'موز',
    nameEnglish: 'banana',
    detailsArabic: 'موز',
    detailsEnglish: 'badddddddddnana',
    mainCategory: 'فواكه',
    subcategory: 'فواكه',
    kilograms: '35',
  },
  {
    id: 2,
    img: img2,
    amount: '4',
    price: '30',
    nameArabic: 'طماطم',
    nameEnglish: 'banana',
    detailsArabic: 'خضروات',
    detailsEnglish: 'banana',
    mainCategory: 'خضروات',
    subcategory: 'خضروات',
    kilograms: '20',
  },
  {
    id: 4,
    img: img4,
    amount: '4',
    price: '30',
    nameArabic: 'خيار',
    nameEnglish: 'banana',
    detailsArabic: 'خيار',
    detailsEnglish: 'banana',
    mainCategory: 'خضروات',
    subcategory: 'خضار',
    kilograms: '7',
  },
  {
    id: 5,
    img: img5,
    amount: '4',
    price: '30',
    nameArabic: 'جاكيت',
    nameEnglish: 'banana',
    detailsArabic: 'جاكيت',
    detailsEnglish: 'banana',
    mainCategory: ' ملابس',
    subcategory: 'جاكيت',
    kilograms: '300',
  },
  {
    id: 6,
    img: img20,
    amount: '4',
    price: '30',
    nameArabic: 'بصل مفروم',
    nameEnglish: 'banana',
    detailsArabic: 'بصل مفروم',
    detailsEnglish: 'banana',
    mainCategory: ' خضروات',
    subcategory: 'خضروات',
    kilograms: '10',
  },
  {
    id: 7,
    img: img7,
    amount: '4',
    price: '30',
    nameArabic: 'ثوم مفروم',
    nameEnglish: 'banana',
    detailsArabic: 'ثوم مفروم',
    detailsEnglish: 'badddddddddnana',
    mainCategory: 'خضروات',
    subcategory: 'خضار',
    kilograms: '16',
  },
  {
    id: 8,
    img: img8,
    amount: '4',
    price: '30',
    nameArabic: 'ثوم فصوص',
    nameEnglish: 'banana',
    detailsArabic: 'خضروات',
    detailsEnglish: 'ثوم فصوص',
    mainCategory: 'خضروات',
    subcategory: 'خضروات',
    kilograms: '12',
  },
  {
    id: 10,
    img: img10,
    amount: '4',
    price: '30',
    nameArabic: 'تفاح',
    nameEnglish: 'banana',
    detailsArabic: 'تفاح',
    detailsEnglish: 'banana',
    mainCategory: 'فواكه',
    subcategory: 'خضار',
    kilograms: '25',
  },
  {
    id: 11,
    img: img11,
    amount: '4',
    price: '30',
    nameArabic: 'فراولة',
    nameEnglish: 'banana',
    detailsArabic: 'فراولة',
    detailsEnglish: 'banana',
    mainCategory: ' فواكه',
    subcategory: 'فواكه',
    kilograms: '40',
  },
  {
    id: 12,
    img: img12,
    amount: '4',
    price: '30',
    nameArabic: 'بطاطس',
    nameEnglish: 'banana',
    detailsArabic: 'بطاطس',
    detailsEnglish: 'banana',
    mainCategory: 'خضروات',
    subcategory: 'خضروات',
    kilograms: '10',
  },
  {
    id: 13,
    img: img13,
    amount: '4',
    price: '30',
    nameArabic: 'ليمون',
    nameEnglish: 'banana',
    detailsArabic: 'ليمون',
    detailsEnglish: 'ليمون',
    mainCategory: 'خضروات',
    subcategory: 'خضار',
    kilograms: '30',
  },
  {
    id: 14,
    img: img14,
    amount: '4',
    price: '30',
    nameArabic: 'بصل أحمر',
    nameEnglish: 'بصل أحمر',
    detailsArabic: 'بصل أحمر',
    detailsEnglish: 'banana',
    mainCategory: 'خضروات',
    subcategory: 'خضار',
    kilograms: '7',
  },
  {
    id: 15,
    img: img15,
    amount: '4',
    price: '30',
    nameArabic: 'بصل شرائح',
    nameEnglish: 'banana',
    detailsArabic: ' خضروات',
    detailsEnglish: 'banana',
    mainCategory: 'خضروات',
    subcategory: 'خضروات',
    kilograms: '15',
  },
  {
    id: 16,
    img: img16,
    amount: '4',
    price: '13',
    nameArabic: 'بصل أبيض',
    nameEnglish: 'بصل أبيض',
    detailsArabic: 'بصل أبيض',
    detailsEnglish: 'banana',
    mainCategory: 'خضروات',
    subcategory: 'خضار',
    kilograms: '13',
  },
  {
    id: 18,
    img: img18,
    amount: '4',
    price: '22',
    nameArabic: 'كوسه متقطعه',
    nameEnglish: 'banana',
    detailsArabic: 'كوسه متقطعه',
    detailsEnglish: 'banana',
    mainCategory: ' خضروات',
    subcategory: 'خضروات',
    kilograms: '22',
  },
  {
    id: 19,
    img: img19,
    amount: '4',
    price: '30',
    nameArabic: 'طماطم متسبكه ',
    nameEnglish: 'banana',
    detailsArabic: 'طماطم متسبكه',
    detailsEnglish: 'badddddddddnana',
    mainCategory: 'خضروات',
    subcategory: 'خضار',
    kilograms: '15',
  },
];
